#!perl -p0
sub i{index$_,shift}
$w=i"\n";
@t=(i(o),i x);
s/[h-l]+.//s;
for$c(split'',$&){eval's/'.('(x(.))/ox','((.)x)/xo','((.)(.{$w})x)/x$3o','x(.{$w})(.)/o$1x')[index"lhkj\n",$c].'/s;push@t,i x;$2eq"-"&&substr$_,shift@t,1,"-"'}
